set nu
set encoding=utf-8
filetype plugin on
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

"style
syntax on
if(&t_Co==256)
    set background=light
    colorscheme solarized
else
    colorscheme desert
endif


set nocompatible
set noswapfile
set nobackup
set nobomb

set nofoldenable
set hlsearch
set ttyfast
set laststatus=2
set fileformats=unix,dos,mac
set cmdheight=2
set title
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
