setopt PROMPT_SUBST
autoload -U promptinit
promptinit
prompt dbi

# Initialize completion
autoload -U compinit
compinit

# Aliases
alias ls='ls --color=auto'
alias ll='ls --color=auto -l'
alias grep='grep --color'


bindkey -e
# fix keybindings
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# User configuration

export EDITOR='vim'
alias public_ip="curl -s http://ipinfo.io/ip"

if [[ -f ~/.zshrc_local ]];then
    . ~/.zshrc_local
fi
