setopt PROMPT_SUBST
autoload -U promptinit
promptinit
prompt dbi

# Initialize completion
autoload -U compinit
compinit

# Aliases
if [[ `uname` == "Darwin" ]];then
    alias ls='ls -G'
    alias ll='ls -G -l'
else
    alias ls='ls --color=auto'
    alias ll='ls --color=auto -l'
fi
alias grep='grep --color'
alias less='less -M'
alias p3serv='python3 -m http.server'


bindkey -e
# fix keybindings
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "${terminfo[kdch1]}" delete-char
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# User configuration
if [[ "$TERM" == "xterm" ]]; then
    export TERM=xterm-256color
fi

export GOPATH=~/gocode

if [[ ! -d $GOPATH ]];then
    mkdir -p $GOPATH
fi
export PATH=~/bin:$GOPATH/bin:$PATH
export EDITOR='vim'
alias public_ip="curl -s http://ipinfo.io/ip"

function find_gitconfig() {
    local GITCONFIG=`rfindfile .gitconfig`
    if [[ -z "${GITCONFIG}" ]];then
        GITCONFIG=$(absp ~/.gitconfig)
    fi
    echo `dirname "${GITCONFIG}"`
}

alias git="HOME=\$(find_gitconfig) git"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
PROMPT_EOL_MARK=''

if [[ -f ~/.zshrc_local ]];then
    . ~/.zshrc_local
fi
